rabbitmq_users:
  - user: "{{ opensrp_rabbitmq_username }}"
    password: "{{ opensrp_rabbitmq_password }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator

rabbitmq_create_cluster: no
rabbitmq_cluster_master: "localhost"
rabbitmq_amqp_port: "{{ opensrp_rabbitmq_port }}"
rabbitmq_erlang_version: 1:24.*
rabbitmq_server_version: 3.9.13-1
rabbitmq_ulimit_open_files: 65536
