---
keycloak_admin_password: "{{ vault_keycloak_admin_password }}"
keycloak_postgresql_password: "{{ vault_keycloak_postgresql_password }}"
keycloak_postgresql_host: "{{ database_host }}"
keycloak_postgresql_user: "keycloak"
keycloak_postgresql_database: "keycloak"
keycloak_postgres_superuser: "{{ reveal_postgres_superuser }}"
keycloak_postgres_superuser_password: "{{ reveal_postgres_superuser_password }}"
keycloak_postgresql_connection_url: "jdbc:postgresql://{{ keycloak_postgresql_host }}:5432/{{ keycloak_postgresql_database }}"
keycloak_http_port: 8080
keycloak_https_port: 8443
keycloak_certs_from_letsencrypt: true
keycloak_nginx_max_filesize: "50M"
keycloak_site_name: "preview-keycloakmhealth.{{ reveal_site_name }}"
keycloak_certbot_mail_address: "techops+{{ keycloak_site_name }}@ona.io"
keycloak_nginx_upstream_url: "https://{{ application_host }}:{{ keycloak_https_port }}"

keycloak_ver: '17.0.1'
keycloak_mirror: https://github.com/keycloak/keycloak/releases/download

keycloak_checksums:
  # https://github.com/keycloak/keycloak/releases/download/16.1.1/keycloak-16.1.1.tar.gz.sha1
  '17.0.1': sha1:5c866e26b95542498c24eeb403225a950bf02027