---
app_env: "preview"
app_title: "Reveal Thailand Preview"

deployed_site_name: "preview-mhealth.{{ reveal_site_name }}"

keycloak_realm: "reveal-thailand-preview"
keycloak_url: "https://preview-keycloakmhealth.ddc-malaria.org"

opensrp_client_id: "reveal-thailand-preview"
opensrp_server_url: "https://preview-servermhealth.{{ reveal_site_name }}"

reveal_app_ga_code: ""
reveal_certbot_mail_address: "techops+{{ deployed_site_name }}@ona.io"
reveal_monit_email_admins:
  - {"Ona Devops", "techops+{{ deployed_site_name }}@ona.io"}
reveal_navbar_brand_img_src: "https://github.com/onaio/reveal-frontend/raw/master/src/assets/images/thai-logo.png"
reveal_enabled_plan_types: "FI,Dynamic-FI"
reveal_map_disabled_plan_types: "FI,Dynamic-FI"
reveal_sentry_dsn: ""

superset_url: "https://preview-supersetmhealth.{{ reveal_site_name }}"
