---
ansible_user: mhealth

# Server monitoring
server_monitoring_set_hostname: true
server_monitoring_hostname_from_ec2_Name_tag: true
collectd_version: "5.*"
monit_version: "1:5*"
collectd_deployed_app_name: "Reveal"
collectd_deployed_app_version: "{{ reveal_react_git_version }}"
# Logstash
reveal_openjdk_version: "8"
reveal_monit_scripts: ["openssh-server"]

deployed_site_name: "mhealth.ddc.moph.go.th"
keycloak_url: "https://keycloakmhealth.ddc.moph.go.th"
opensrp_server_url: "https://servermhealth.ddc.moph.go.th"
opensrp_client_id: "reveal-thailand-production"
keycloak_realm: "reveal-thailand-production"
superset_url: "https://supersetmhealth.ddc.moph.go.th"

# reveal-web
reveal_react_remote_js_build: false
reveal_map_disabled_plan_types: "Dynamic-FI"
reveal_enabled_plan_types: "Dynamic-FI"
# react
reveal_react_system_user: "revealweb"
reveal_react_system_user_home: "/home/{{ reveal_react_system_user }}"
reveal_react_codebase_path: "{{ reveal_react_system_user_home }}/react"
reveal_react_public_dir: "{{ reveal_react_codebase_path }}/build"
reveal_react_git_url: "https://github.com/onaio/reveal-frontend.git"
reveal_react_git_version: "v1.9.6"
reveal_react_git_key:
reveal_react_node_version: "16.x"
reveal_react_build_cmds:
  - cmd: build
    path: "{{ react_local_app_path }}"
reveal_react_app_settings:
  GENERATE_SOURCEMAP: 'false'
  SKIP_PREFLIGHT_CHECK: 'true'
  INLINE_RUNTIME_CHUNK: "false"
  IMAGE_INLINE_SIZE_LIMIT: "0"
  REACT_APP_DOMAIN_NAME: "https://{{ deployed_site_name }}"
  REACT_APP_WEBSITE_NAME: "{{ app_title }}"
  REACT_APP_THEME_COLOR: "000000"
  REACT_APP_LANGUAGE: "th"
  REACT_APP_GA_CODE: "{{ reveal_app_ga_code }}"
  REACT_APP_GA_ENV: "{{ app_env }}"
  REACT_APP_ENABLE_IRS: "false"
  REACT_APP_ENABLE_FI: "true"
  REACT_APP_ENABLE_USERS: "false"
  REACT_APP_ENABLE_ABOUT: "false"
  REACT_APP_ENABLE_ASSIGN: "false"
  REACT_APP_ENABLE_TEAMS: "false"
  REACT_APP_ENABLE_PRACTITIONERS: "false"
  REACT_APP_DISABLE_LOGIN_PROTECTION: "false"
  REACT_APP_SUPERSET_API_BASE: "{{ superset_url }}/"
  REACT_APP_SUPERSET_API_ENDPOINT: slice
  REACT_APP_SUPERSET_MAX_RECORDS: 15000
  REACT_APP_SUPERSET_PLANS_SLICE: 1
  REACT_APP_SUPERSET_GOALS_SLICE: 3
  REACT_APP_SUPERSET_JURISDICTIONS_SLICE: 2
  REACT_APP_SUPERSET_STRUCTURES_SLICE: 4
  REACT_APP_SUPERSET_JURISDICTIONS_DATA_SLICE: 5
  REACT_APP_SUPERSET_PLAN_STRUCTURE_PIVOT_SLICE: 6
  REACT_APP_SUPERSET_PLANS_TABLE_SLICE: 7
  REACT_APP_SUPERSET_TASKS_SLICE: 8
  REACT_APP_SUPERSET_JURISDICTION_EVENTS_SLICE: 9
  REACT_APP_ENABLE_OPENSRP_OAUTH: "true"
  REACT_APP_OPENSRP_CLIENT_ID: "{{ opensrp_client_id }}"
  REACT_APP_OPENSRP_ACCESS_TOKEN_URL: "{{ keycloak_url }}/auth/realms/{{ keycloak_realm }}/protocol/openid-connect/token"
  REACT_APP_OPENSRP_AUTHORIZATION_URL: "{{ keycloak_url }}/auth/realms/{{ keycloak_realm }}/protocol/openid-connect/auth"
  REACT_APP_OPENSRP_USER_URL: "{{ opensrp_server_url }}/opensrp/user-details"
  REACT_APP_OPENSRP_API_BASE_URL: "{{ opensrp_server_url }}/opensrp/rest/"
  REACT_APP_OAUTH_GET_STATE_URL: "https://{{ deployed_site_name }}/oauth/state"
  REACT_APP_REACT_APP_OPENSRP_OAUTH_STATE: opensrp
  REACT_APP_ENABLE_ONADATA_OAUTH: "false"
  REACT_APP_DATE_FORMAT: yyyy-MM-dd
  REACT_APP_DEFAULT_PLAN_DURATION_DAYS: 20
  REACT_APP_PLAN_VERSION: 1
  REACT_APP_ENV: "{{ app_env }}"
  REACT_APP_EXPRESS_OAUTH_LOGOUT_URL: "https://{{ deployed_site_name }}/logout"
  REACT_APP_EXPRESS_OAUTH_GET_STATE_URL: "https://{{ deployed_site_name }}/oauth/state"
  REACT_APP_KEYCLOAK_LOGOUT_URL: "{{ keycloak_url }}/auth/realms/{{ keycloak_realm }}/protocol/openid-connect/logout"
  REACT_APP_BACKEND_ACTIVE: "true"
  REACT_APP_VERSION: "$npm_package_version"
  REACT_APP_NAME: "$npm_package_name"
  REACT_APP_ENABLE_MDA_POINT: "false"
  REACT_APP_OPENSRP_LOGOUT_URL: '{{ opensrp_server_url }}/opensrp/logout.do'
  REACT_APP_DISPLAYED_PLAN_TYPES: "FI,Dynamic-FI"
  REACT_APP_PLAN_TYPES_ALLOWED_TO_CREATE: "Dynamic-FI"
  REACT_APP_NAVBAR_BRAND_IMG_SRC: "https://github.com/onaio/reveal-frontend/raw/{{reveal_react_git_version}}/src/assets/images/thai-logo.png"
  REACT_APP_REVEAL_BRAND_IMG_SRC: "https://github.com/onaio/reveal-frontend/raw/{{reveal_react_git_version}}/src/assets/images/logo-small.png"
  REACT_APP_SHOW_MDA_SCHOOL_REPORT_LABEL: "false"
  REACT_APP_ENABLE_JURISDICTION_METADATA_UPLOAD: "false"
  REACT_APP_ENABLE_CONFIG_FORM: "true"
  REACT_APP_ENABLE_POPULATION_SERVER_SETTINGS: "false"
  REACT_APP_OPENSRP_API_V2_BASE_URL: "{{ opensrp_server_url }}/opensrp/rest/v2/"
  REACT_APP_ENABLE_PLANNING: "false"
  REACT_APP_SENTRY_DSN: "{{ reveal_sentry_dsn }}"
  REACT_APP_ENABLE_JURISDICTIONS_AUTO_SELECTION: "false"
  REACT_APP_HIDDEN_PLAN_STATUSES: retired
  REACT_APP_MAP_DISABLED_PLAN_TYPES: "{{ reveal_map_disabled_plan_types }}"
  REACT_APP_ASSIGNMENT_PAGE_SHOW_MAP: "false"
  REACT_APP_GISIDA_MAPBOX_TOKEN: pk.eyJ1IjoidGhhaWxhbmRidmJkIiwiYSI6ImNqdnh4b3d6NTBhNW4zeXBjc243OXpmamgifQ.5eHgZf6XwbUV8tvkmlOLZw
  REACT_APP_SHOW_TEAM_ASSIGN_ON_OPERATIONAL_AREAS_ONLY: "true"
  REACT_APP_ENABLE_HOME_MANAGE_PLANS_LINK: "true"
  REACT_APP_ENABLE_HOME_PLANNING_VIEW_LINK: "false"
  REACT_APP_ENABLE_DEFAULT_PLAN_USER_FILTER: "true"
  REACT_APP_ENABLED_FI_REASONS: Routine
  REACT_APP_OPENSRP_MAX_PLANS_PER_REQUEST: 4000
  REACT_APP_CHECK_SESSION_EXPIRY_STATUS: "true"
  REACT_APP_PLAN_LIST_SHOW_FI_REASON_COLUMN: "true"
  REACT_APP_AUTO_SELECT_FI_CLASSIFICATION: "true"
  REACT_APP_CASE_TRIGGERED_DRAFT_EDIT_ADD_ACTIVITIES: "true"
  REACT_APP_HIDE_PLAN_FORM_FIELDS_ON_EDIT: "interventionType,fiReason,activityActionTitle,activityActionReason,activityActionDefinitionUri,activityTimingPeriodStart,activityTimingPeriodEnd,activityGoalPriority,triggersAndConditions"
  REACT_APP_HIDE_PLAN_FORM_FIELDS_ON_CREATE: "interventionType,fiReason,activityActionTitle,activityActionReason,activityActionDefinitionUri,activityTimingPeriodStart,activityTimingPeriodEnd,activityGoalPriority,triggersAndConditions"
  REACT_APP_AUTO_ENABLE_NAVIGATION_TO: "/assign"
  REACT_APP_REVOKE_COMPLETE_AND_RETIRED_PLANS_TEAM_ASSIGNMENTS: "false"
  REACT_APP_OPENSRP_GENERATED_TASKS_INTERVENTIONS: "Dynamic-FI"

# express
reveal_express_system_user: "{{ reveal_react_system_user }}"
reveal_express_system_user_home: "/home/{{ reveal_express_system_user }}"

# git
reveal_express_git_url: "https://github.com/onaio/express-server.git"
reveal_express_git_version: "v1.2.0"
reveal_express_git_key:
# app
reveal_express_app_name: "{{ express_system_user }}"
reveal_express_codebase_path: "{{ express_system_user_home }}/express"
reveal_express_app_path: "{{ express_checkout_path }}"
reveal_express_log_path: "/var/log/{{ express_app_name }}"
reveal_express_app_settings:
  NODE_ENV: "{{ app_env }}"
  EXPRESS_OPENSRP_ACCESS_TOKEN_URL: "{{ keycloak_url }}/auth/realms/{{ keycloak_realm }}/protocol/openid-connect/token"
  EXPRESS_OPENSRP_AUTHORIZATION_URL: "{{ keycloak_url }}/auth/realms/{{ keycloak_realm }}/protocol/openid-connect/auth"
  EXPRESS_OPENSRP_USER_URL: "{{ opensrp_server_url }}/opensrp/user-details"
  EXPRESS_OPENSRP_OAUTH_STATE: "opensrp"
  EXPRESS_OPENSRP_CALLBACK_URL: "https://{{ deployed_site_name }}/oauth/callback/OpenSRP/"
  EXPRESS_OAUTH_GET_STATE_URL: "https://{{ deployed_site_name }}/oauth/state"
  EXPRESS_PORT: "3000"
  EXPRESS_SESSION_NAME: "reveal-session"
  EXPRESS_SESSION_SECRET: "{{ vault_express_session_secret }}"
  EXPRESS_SESSION_PATH: "/"
  EXPRESS_REACT_BUILD_PATH: "{{ reveal_react_public_dir }}"
  EXPRESS_SESSION_FILESTORE_PATH: "/tmp/express-sessions"
  EXPRESS_PRELOADED_STATE_FILE: "/tmp/revealState.json"
  EXPRESS_SESSION_LOGIN_URL: "/login"
  EXPRESS_FRONTEND_OPENSRP_CALLBACK_URL: "https://{{ deployed_site_name }}/fe/oauth/callback/opensrp"
  EXPRESS_OPENSRP_CLIENT_ID: "{{ opensrp_client_id }}"
  EXPRESS_OPENSRP_CLIENT_SECRET: "{{ vault_express_opensrp_client_secret }}"
  EXPRESS_FRONTEND_LOGIN_URL: "/fe/login"
  EXPRESS_SERVER_LOGOUT_URL: "https://{{ deployed_site_name }}/logout"
  EXPRESS_OPENSRP_LOGOUT_URL: "{{ opensrp_server_url }}/opensrp/logout.do"
  EXPRESS_KEYCLOAK_LOGOUT_URL: "{{ keycloak_url }}/auth/realms/{{ keycloak_realm }}/protocol/openid-connect/logout"
  EXPRESS_MAXIMUM_LOGS_FILE_SIZE: 5242880
  EXPRESS_MAXIMUM_LOG_FILES_NUMBER: 5
  EXRESS_LOGS_FILE_PATH: "/tmp/logs/reveal-express-server.log"
  EXPRESS_ALLOW_TOKEN_RENEWAL: "true"
  EXPRESS_MAXIMUM_SESSION_LIFE_TIME: 10800
  EXPRESS_CONTENT_SECURITY_POLICY_CONFIG: '{
    "script-src": ["''self''","''unsafe-inline''","''unsafe-eval''","https://cdnjs.cloudflare.com","code.jquery.com"],
    "img-src": ["''self''","https://github.com","https://*.githubusercontent.com","data:"],
    "connect-src": ["''self''","{{ superset_url | string }}","{{ keycloak_url | string }}","{{ opensrp_server_url | string }}"]
    }'

# nginx
nginx_install_only: true
nginx_version: "1.18.*"
reveal_nginx_site_names:
  - "{{ deployed_site_name }}"
reveal_nginx_site_name: "{{ reveal_nginx_site_names[0] }}"
reveal_nginx_http_site_name: "{{ deployed_site_name }}-http"
reveal_nginx_https_site_name: "{{ deployed_site_name }}-https"
reveal_nginx_access_logs:
  - name: "timed_combined"
    format: "'$http_x_forwarded_for - $remote_user [$time_local]  \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $request_time $upstream_response_time $gzip_ratio $request_length'"
    options: null
    filename: "access.log"
reveal_nginx_enabled_sites:
  - "{{ reveal_nginx_http_site_name }}"
  - "{{ reveal_nginx_https_site_name }}"
reveal_nginx_ssl_dir: /etc/nginx/ssl/{{ deployed_site_name }}
reveal_nginx_sites:
  - server:
      name: "{{ reveal_nginx_http_site_name }}"
      listen:
        - "80"
        - "[::]:80"
      server_name: "{{ reveal_nginx_site_names|join(' ') }}"
      access_log: "{{ reveal_nginx_log_path }}/{{ deployed_site_name }}-access.log timed_combined"
      error_log: "{{ reveal_nginx_log_path }}/{{ deployed_site_name }}-error.log"
      rewrite: "^(.*) https://{{ reveal_nginx_site_name }}$1 permanent"
      ssl:
        enabled: false
  - server:
      name: "{{ reveal_nginx_https_site_name }}"
      listen:
        - "443 ssl"
        - "[::]:443 ssl"
      server_name: "{{ reveal_nginx_site_names|join(' ') }}"
      access_log: "{{ reveal_nginx_log_path }}/{{ deployed_site_name }}-ssl-access.log timed_combined"
      error_log: "{{ reveal_nginx_log_path }}/{{ deployed_site_name }}-ssl-error.log"
      ssl:
        access_log_format: "timed_combined"
        enabled: true
        remote_src: false
        create_symlink: false
        cert: "{{ reveal_ssl_cert_file }}"
        key: "{{ reveal_ssl_key_file }}"
        src_dir: "{{ reveal_ssl_dir }}"
        conf: "{{ deployed_site_name }}.conf"
      # do not cache the service worker
      location1:
        name: "/service-worker.js"
        add_header: 'Cache-Control "no-cache"'
        proxy_cache_bypass: "$http_pragma"
        proxy_cache_revalidate: "on"
        expires: "off"
        access_log: "off"
      location2:
        name: "/"
        autoindex: "off"
        charset: "UTF-8"
        proxy_pass: http://localhost:3000
        proxy_http_version: 1.1
        proxy_set_header:
          - "Upgrade $http_upgrade"
          - "Connection 'upgrade'"
          - "Host $host"
          - "X-Forwarded-Proto https"
        proxy_cache_bypass: $http_upgrade
reveal_nginx_monit_protection: false
reveal_nginx_log_path: "/var/log/nginx/"
reveal_nginx_large_client_header_buffers: "4 8k"
reveal_nginx_first_start: true

# certbot
reveal_use_certbot: false
reveal_certbot_create_certs: false
reveal_certbot_renew_certs: false
reveal_certbot_install_cert: false
reveal_certbot_package: "python3-certbot-nginx"
reveal_certbot_version: "0.40.*"
reveal_certbot_site_names:
  - "{{ deployed_site_name }}"

slack_deployed_app_name: "{{ app_title }}"
slack_deployed_app_version: "{{ reveal_react_git_version }}"
slack_deployed_domain: "{{ deployed_site_name }}"

# Logstash
logstash_major_ver: "7.x"
logstash_minor_ver: "1:7.*"
clear_logstash_config: true
logstash_system_groups: ["adm"]
config_logstash: true
logstash_plugins:
  - name: logstash-output-gelf
    state: present
logstash_custom_outputs:
  - output: 'gelf'
    lines:
      - 'host => "{{ graylog_server }}"'
      - 'port => "{{ graylog_port }}"'
      - 'sender => "{{ reveal_react_git_version }}"'
logstash_custom_inputs:
  - input: 'file'
    lines:
      - 'path => ["{{ reveal_nginx_log_path }}{{ deployed_site_name }}-ssl-access.log"]'
      - 'start_position => "end"'
      - 'add_field => {'
      - '  ssl => false'
      - '  nginx_access => true'
      - '  from_nginx => true'
      - '  from_ona => false'
      - '  from_host => "%{host}"'
      - '  from_domain => "{{ deployed_site_name }}"'
      - '  from_{{ reveal_react_system_user }} => true'
      - '  git_version => "{{ reveal_react_git_version }}"'
      - '}'
logstash_openjdk_version: "{{ reveal_openjdk_version }}"
